# Generated by Django 4.2.1 on 2023-05-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopictureadd',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
